### ISSUE TITLE
Token should expose a public destroy() method.

### ISSUE THREAD

**Issue by ma2ciek** [ckeditor/ckeditor-cloud-services-core#9]
For now, the only exposed method that stops the interval in Token is the protected `_stopListening` method.

**Comment by pjasiun** [comment]
Moved from duplicate:

When the token class is not needed anymore it should stop refreshing. To do so, it should have a public method. I would call it destroy (since there is init). The case is that the CKEditor using this class is destroyed and the token is still refreshing.

And yea, I know I am the one who insists on making _startRefreshing and _stopRefreshing private, but I forget about this case then.
